#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.


#IfWinActive ahk_class Notepad
::btw:: 

(
By the way: Any text between the top and bottom parentheses is treated literally, including commas and percent signs.
By default, the hard carriage return (Enter) between the previous line and this one is also preserved.
    By default, the indentation (tab) to the left of this line is preserved.
)
#IfWinActive
::btw::By the way,

::brb::Be right back.

::ocularum::
(
Ocularomonoturnolamphrolamphrodynogravitoquarkoelectroleptofermiophotogluomesobosoprotoneutrobaryohadroatomoleculounicellulocrystolattissomicromegalobiogaiamatechniotellagaiaselenasolaraperinebulavacuooriocygnobrachiogalactoproximasystadavirgolaniakeasuperclustopiscescetusfilamentocytosis
)



::my email::
(
my email: *********@gmail.com
)

::brb::
(
be right back
)

::mymail::
(
***********@gmail.com
)

::randomWoords::
(
spheropeople
spherohistory
spheroway
spheroart
spheroworld
spheroinformation
spheromap
spherotwo
spherofamily
spherogovernment
spherohealth
spherosystem
spherocomputer
spheromeat
spheroyear
spherothanks
spheromusic
spheroperson
spheroreading
spheromethod
spherodata
spherofood
spherounderstanding
spherotheory
spherolaw
spherobird
spheroliterature
spheroproblem
spherosoftware
spherocontrol
spheroknowledge
spheropower
spheroability
spheroeconomics
spherolove
spherointernet
spherotelevision
spheroscience
spherolibrary
spheronature
spherofact
spheroproduct
spheroidea
spherotemperature
spheroinvestment
spheroarea
spherosociety
spheroactivity
spherostory
spheroindustry
spheromedia
spherothing
spherooven
spherocommunity
spherodefinition
spherosafety
spheroquality
spherodevelopment
spherolanguage
spheromanagement
spheroplayer
spherovariety
spherovideo
spheroweek
spherosecurity
spherocountry
spheroexam
spheromovie
spheroorganization
spheroequipment
spherophysics
spheroanalysis
spheropolicy
spheroseries
spherothought
spherobasis
spheroboyfriend
spherodirection
spherostrategy
spherotechnology
spheroarmy
spherocamera
spherofreedom
spheropaper
spheroenvironment
spherochild
spheroinstance
spheromonth
spherotruth
spheromarketing
spherouniversity
spherowriting
spheroarticle
spherodepartment
spherodifference
spherogoal
spheronews
spheroaudience
spherofishing
spherogrowth
spheroincome
)

::moreRandomWoords::
(
spheromarriage
spherouser
spherocombination
spherofailure
spheromeaning
spheromedicine
spherophilosophy
spheroteacher
spherocommunication
spheronight
spherochemistry
spherodisease
spherodisk
spheroenergy
spheronation
spheroroad
spherorole
spherosoup
spheroadvertising
spherolocation
spherosuccess
spheroaddition
spheroapartment
spheroeducation
spheromath
spheromoment
spheropainting
spheropolitics
spheroattention
spherodecision
spheroevent
spheroproperty
spheroshopping
spherostudent
spherowood
spherocompetition
spherodistribution
spheroentertainment
spherooffice
spheropopulation
spheropresident
spherounit
spherocategory
spherocigarette
spherocontext
spherointroduction
spheroopportunity
spheroperformance
spherodriver
spheroflight
spherolength
spheromagazine
spheronewspaper
spherorelationship
spheroteaching
spherocell
spherodealer
spherofinding
spherolake
spheromember
spheromessage
spherophone
spheroscene
spheroappearance
spheroassociation
spheroconcept
spherocustomer
spherodeath
spherodiscussion
spherohousing
spheroinflation
spheroinsurance
spheromood
spherowoman
spheroadvice
spheroblood
spheroeffort
spheroexpression
spheroimportance
spheroopinion
spheropayment
spheroreality
spheroresponsibility
spherosituation
spheroskill
spherostatement
spherowealth
spheroapplication
spherocity
spherocounty
spherodepth
spheroestate
spherofoundation
spherograndmother
spheroheart
spheroperspective
spherophoto
spherorecipe
spherostudio
spherotopic
)

::evenMoreRandomWoords::
(
spherocollection
spherodepression
spheroimagination
spheropassion
spheropercentage
spheroresource
spherosetting
spheroad
spheroagency
spherocollege
spheroconnection
spherocriticism
spherodebt
spherodescription
spheromemory
spheropatience
spherosecretary
spherosolution
spheroadministration
spheroaspect
spheroattitude
spherodirector
spheropersonality
spheropsychology
spherorecommendation
spheroresponse
spheroselection
spherostorage
spheroversion
spheroalcohol
spheroargument
spherocomplaint
spherocontract
spheroemphasis
spherohighway
spheroloss
spheromembership
spheropossession
spheropreparation
spherosteak
spherounion
spheroagreement
spherocancer
spherocurrency
spheroemployment
spheroengineering
spheroentry
spherointeraction
spheromixture
spheropreference
spheroregion
spherorepublic
spherotradition
spherovirus
spheroactor
spheroclassroom
spherodelivery
spherodevice
spherodifficulty
spherodrama
spheroelection
spheroengine
spherofootball
spheroguidance
spherohotel
spheroowner
spheropriority
spheroprotection
spherosuggestion
spherotension
spherovariation
spheroanxiety
spheroatmosphere
spheroawareness
spherobath
spherobread
spherocandidate
spheroclimate
spherocomparison
spheroconfusion
spheroconstruction
spheroelevator
spheroemotion
spheroemployee
spheroemployer
spheroguest
spheroheight
spheroleadership
spheromall
spheromanager
spherooperation
spherorecording
spherosample
spherotransportation
spherocharity
spherocousin
spherodisaster
spheroeditor
spheroefficiency
spheroexcitement
)

::randomWoords4::
(
spheroextent
spherofeedback
spheroguitar
spherohomework
spheroleader
spheromom
spherooutcome
spheropermission
spheropresentation
spheropromotion
spheroreflection
spherorefrigerator
spheroresolution
spherorevenue
spherosession
spherosinger
spherotennis
spherobasket
spherobonus
spherocabinet
spherochildhood
spherochurch
spheroclothes
spherocoffee
spherodinner
spherodrawing
spherohair
spherohearing
spheroinitiative
spherojudgment
spherolab
spheromeasurement
spheromode
spheromud
spheroorange
spheropoetry
spheropolice
spheropossibility
spheroprocedure
spheroqueen
spheroratio
spherorelation
spherorestaurant
spherosatisfaction
spherosector
spherosignature
spherosignificance
spherosong
spherotooth
spherotown
spherovehicle
spherovolume
spherowife
spheroaccident
spheroairport
spheroappointment
spheroarrival
spheroassumption
spherobaseball
spherochapter
spherocommittee
spheroconversation
spherodatabase
spheroenthusiasm
spheroerror
spheroexplanation
spherofarmer
spherogate
spherogirl
spherohall
spherohistorian
spherohospital
spheroinjury
spheroinstruction
spheromaintenance
spheromanufacturer
spheromeal
spheroperception
spheropie
spheropoem
spheropresence
spheroproposal
spheroreception
spheroreplacement
spherorevolution
spheroriver
spheroson
spherospeech
spherotea
spherovillage
spherowarning
spherowinner
)

::randomWoords5::
(
spheroworker
spherowriter
spheroassistance
spherobreath
spherobuyer
spherochest
spherochocolate
spheroconclusion
spherocontribution
spherocookie
spherocourage
spherodad
spherodesk
spherodrawer
spheroestablishment
spheroexamination
spherogarbage
spherogrocery
spherohoney
spheroimpression
spheroimprovement
spheroindependence
spheroinsect
spheroinspection
spheroinspector
spheroking
spheroladder
spheromenu
spheropenalty
spheropiano
spheropotato
spheroprofession
spheroprofessor
spheroquantity
spheroreaction
spherorequirement
spherosalad
spherosister
spherosupermarket
spherotongue
spheroweakness
spherowedding
spheroaffair
spheroambition
spheroanalyst
spheroapple
spheroassignment
spheroassistant
spherobathroom
spherobedroom
spherobeer
spherobirthday
spherocelebration
spherochampionship
spherocheek
spheroclient
spheroconsequence
spherodeparture
spherodiamond
spherodirt
spheroear
spherofortune
spherofriendship
spherofuneral
spherogene
spherogirlfriend
spherohat
spheroindication
spherointention
spherolady
spheromidnight
spheronegotiation
spheroobligation
spheropassenger
spheropizza
spheroplatform
spheropoet
spheropollution
spherorecognition
spheroreputation
spheroshirt
spherosir
spherospeaker
spherostranger
spherosurgery
spherosympathy
spherotale
spherothroat
spherotrainer
spherouncle
spheroyouth
spherotime
spherowork
spherofilm
spherowater
spheromoney
)

::randomWoords6::
(
spheroexample
spherowhile
spherobusiness
spherostudy
spherogame
spherolife
spheroform
spheroair
spheroday
spheroplace
spheronumber
spheropart
spherofield
spherofish
spheroback
spheroprocess
spheroheat
spherohand
spheroexperience
spherojob
)

::randomWoordList::
(
randomWoords
moreRandomWoords
evenMoreRandomWoords
randomWoords4
randomWoords5
randomWoords6
)


::bif::
(
abs()	delattr()	hash()	memoryview()	set()
all()	dict()	help()	min()	setattr()
any()	dir()	hex()	next()	slice()
ascii()	divmod()	id()	object()	sorted()
bin()	enumerate()	input()	oct()	staticmethod()
bool()	eval()	int()	open()	str()
breakpoint()	exec()	isinstance()	ord()	sum()
bytearray()	filter()	issubclass()	pow()	super()
bytes()	float()	iter()	print()	tuple()
callable()	format()	len()	property()	type()
chr()	frozenset()	list()	range()	vars()
) 

::python comparison operators::
(
Operation	Meaning
<	strictly less than
<=	less than or equal
>	strictly greater than
>=	greater than or equal
==	equal
!=	not equal
is	object identity
is not	negated object identity
)

^g::
Send,^c
Sleep 200
Run, http://www.google.com/search?q=%clipboard%
Return

